// <auto-generated />
using System;
using JobTracker2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobTracker2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("JobTracker2.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("MonthId");

                    b.HasIndex("YearId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            City = "New York",
                            Company = "TechCorp",
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthId = 12,
                            Position = "Software Engineer",
                            YearId = "2025"
                        },
                        new
                        {
                            JobId = 2,
                            City = "San Francisco",
                            Company = "Innovatech",
                            Date = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthId = 1,
                            Position = "Data Analyst",
                            YearId = "2026"
                        });
                });

            modelBuilder.Entity("JobTracker2.Models.Month", b =>
                {
                    b.Property<int>("MonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mon")
                        .HasColumnType("TEXT")
                        .HasColumnName("Month");

                    b.HasKey("MonthId");

                    b.ToTable("Months");

                    b.HasData(
                        new
                        {
                            MonthId = 1,
                            Mon = "January"
                        },
                        new
                        {
                            MonthId = 2,
                            Mon = "February"
                        },
                        new
                        {
                            MonthId = 3,
                            Mon = "March"
                        },
                        new
                        {
                            MonthId = 4,
                            Mon = "April"
                        },
                        new
                        {
                            MonthId = 5,
                            Mon = "May"
                        },
                        new
                        {
                            MonthId = 6,
                            Mon = "June"
                        },
                        new
                        {
                            MonthId = 7,
                            Mon = "July"
                        },
                        new
                        {
                            MonthId = 8,
                            Mon = "August"
                        },
                        new
                        {
                            MonthId = 9,
                            Mon = "September"
                        },
                        new
                        {
                            MonthId = 10,
                            Mon = "October"
                        },
                        new
                        {
                            MonthId = 11,
                            Mon = "November"
                        },
                        new
                        {
                            MonthId = 12,
                            Mon = "December"
                        });
                });

            modelBuilder.Entity("JobTracker2.Models.Year", b =>
                {
                    b.Property<string>("YearId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Yr")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.HasKey("YearId");

                    b.ToTable("Years");

                    b.HasData(
                        new
                        {
                            YearId = "2025",
                            Yr = 2025
                        },
                        new
                        {
                            YearId = "2026",
                            Yr = 2026
                        });
                });

            modelBuilder.Entity("JobTracker2.Models.YearMonth", b =>
                {
                    b.Property<int>("YearMonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("YearMonthId");

                    b.HasIndex("MonthId");

                    b.HasIndex("YearId");

                    b.ToTable("YearMonths");

                    b.HasData(
                        new
                        {
                            YearMonthId = 1,
                            MonthId = 12,
                            YearId = "2025"
                        },
                        new
                        {
                            YearMonthId = 2,
                            MonthId = 1,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 3,
                            MonthId = 2,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 4,
                            MonthId = 3,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 5,
                            MonthId = 4,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 6,
                            MonthId = 5,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 7,
                            MonthId = 6,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 8,
                            MonthId = 7,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 9,
                            MonthId = 8,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 10,
                            MonthId = 9,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 11,
                            MonthId = 10,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 12,
                            MonthId = 11,
                            YearId = "2026"
                        },
                        new
                        {
                            YearMonthId = 13,
                            MonthId = 12,
                            YearId = "2026"
                        });
                });

            modelBuilder.Entity("JobTracker2.Models.Job", b =>
                {
                    b.HasOne("JobTracker2.Models.Month", "Month")
                        .WithMany("Jobs")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobTracker2.Models.Year", "Year")
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("JobTracker2.Models.YearMonth", b =>
                {
                    b.HasOne("JobTracker2.Models.Month", "Month")
                        .WithMany("YearMonths")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobTracker2.Models.Year", "Year")
                        .WithMany("YearMonths")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("JobTracker2.Models.Month", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("YearMonths");
                });

            modelBuilder.Entity("JobTracker2.Models.Year", b =>
                {
                    b.Navigation("YearMonths");
                });
#pragma warning restore 612, 618
        }
    }
}
